spring:
  datasource:
    #数据库 地址 用户名 密码  以及驱动 此处报错不影响启动（设置的是启动加载驱动）
    url: jdbc:mysql://192.168.55.62:3306/wms_gj
    username: root
    password: 360jk
    driver-class-name: com.mysql.jdbc.Driver
#  mvc:
#    view:
#      # 定位模板的目录
#      prefix: /views/
#      # 给返回的页面添加后缀名
#      suffix: .html

  # 选择加载不同环境的配置文件
  profiles:
    active: dev  #生产环境下改成“prod”

#  spring.resources.chain.strategy.content.enabled=true
#  spring.resources.chain.strategy.content.paths=/**
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
   #spring-session 使用
  session:
    store-type: none
mybatis:
  #实体包位置
  type-aliases-package: com.example.demo
  #xml位置
  mapper-locations: classpath:mapper/*.xml
server:
  port: 80
